name: Build and Deploy Physics Site
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      # This step will show us all the files in the repository
      - name: List files in the repository
        run: ls -R

      - name: Deploy
        run: mkdocs gh-deploy --force
